# Generated by Django 6.0 on 2025-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Control', '0002_cursu_rabotau_studentu_remove_course_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('student_lastname', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('completion_status', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python')], max_length=100, verbose_name='Завершенный курс')),
                ('start_date', models.DateField(verbose_name='Дата запуска курса')),
                ('duration_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_hired', models.BooleanField(default=False, verbose_name='Берем в работу?')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Записи на курсы',
            },
        ),
        migrations.CreateModel(
            name='StaffManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('position', models.CharField(choices=[('teacher', 'Учитель'), ('programmer', 'Программист'), ('manager', 'Менеджер'), ('seller', 'Продавец'), ('agent', 'Агент')], max_length=200, verbose_name='Кем работает')),
                ('has_experience', models.BooleanField(default=False, verbose_name='Опыт работы')),
                ('salary', models.IntegerField(verbose_name='Сколько получает')),
                ('is_terminated', models.BooleanField(default=False, verbose_name='Уволен?')),
            ],
            options={
                'verbose_name': 'Управление персоналом',
                'verbose_name_plural': 'Управление персоналом',
            },
        ),
        migrations.CreateModel(
            name='StudentManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('attendance_status', models.CharField(choices=[('late', 'Опоздал'), ('on_time', 'Вовремя')], max_length=100, verbose_name='Статус опоздания')),
                ('start_date', models.DateField(verbose_name='Дата начала обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплатил или нет')),
                ('is_graduated', models.BooleanField(default=False, verbose_name='Закончил или нет')),
            ],
            options={
                'verbose_name': 'Управление студентом',
                'verbose_name_plural': 'Управление студентами',
            },
        ),
        migrations.DeleteModel(
            name='cursu',
        ),
        migrations.DeleteModel(
            name='rabotau',
        ),
        migrations.DeleteModel(
            name='studentu',
        ),
    ]
