# Generated by Django 6.0 on 2025-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_Control', '0003_courseenrollment_staffmanagement_studentmanagement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmanagement',
            options={'verbose_name': 'Управление работ', 'verbose_name_plural': 'Управление работы'},
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='completion_status',
            field=models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python')], max_length=100, verbose_name='Закончил курс'),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='is_hired',
            field=models.BooleanField(default=False, verbose_name='Берем в работу:'),
        ),
        migrations.AlterField(
            model_name='staffmanagement',
            name='is_terminated',
            field=models.BooleanField(default=False, verbose_name='в работе:'),
        ),
        migrations.AlterField(
            model_name='studentmanagement',
            name='attendance_status',
            field=models.CharField(choices=[('late', 'Опоздал'), ('on_time', 'Вовремя')], max_length=100, verbose_name='опоздал:'),
        ),
    ]
