# Generated by Django 6.0 on 2025-12-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidzaiavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.CharField(max_length=20, verbose_name='номер')),
                ('paid', models.BooleanField(default=False, verbose_name='нажмите на кнопку отправить')),
            ],
            options={
                'verbose_name': 'fullcode',
                'verbose_name_plural': 'fullcodes',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='загрузка фото')),
                ('name', models.CharField(max_length=100, verbose_name='имия')),
                ('text', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'команды',
                'verbose_name_plural': 'команды',
            },
        ),
        migrations.CreateModel(
            name='Osavatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fro', models.CharField(max_length=120, verbose_name='оснаватели компании')),
                ('text', models.TextField(verbose_name='подробнее')),
                ('img', models.ImageField(upload_to='загрузить')),
                ('title', models.CharField(max_length=100, verbose_name='имия оснавателя')),
            ],
            options={
                'verbose_name': 'оснаветель',
                'verbose_name_plural': 'оснаватели',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='проекты')),
                ('title', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'наш проект',
                'verbose_name_plural': 'наши проекты',
            },
        ),
        migrations.CreateModel(
            name='Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usluga', models.CharField(max_length=100, verbose_name='товар')),
                ('text', models.TextField(verbose_name='подробнее описание')),
                ('img', models.ImageField(upload_to='услуга')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
    ]
