# Generated by Django 6.0 on 2025-12-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Логотип', verbose_name='Логотипы')),
                ('description', models.CharField(max_length=35, verbose_name='Название логотип')),
            ],
            options={
                'verbose_name': 'Логотипы',
                'verbose_name_plural': 'Логотип',
            },
        ),
    ]
