# Generated by Django 6.0 on 2025-12-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_development', '0002_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('name1', models.CharField(max_length=100, verbose_name='Все прова защишены')),
                ('name2', models.CharField(max_length=100, verbose_name='Услуги')),
                ('name3', models.CharField(max_length=100, verbose_name='АЙти Школа')),
                ('name4', models.CharField(max_length=100, verbose_name='Проекты')),
                ('name5', models.CharField(max_length=100, verbose_name='Команда')),
                ('img', models.ImageField(upload_to='Иконки', verbose_name='Иконки')),
                ('img2', models.ImageField(upload_to='Иконки', verbose_name='Иконки')),
                ('img3', models.ImageField(upload_to='Иконки', verbose_name='Иконки')),
                ('img4', models.ImageField(upload_to='Иконки', verbose_name='Иконки')),
            ],
        ),
    ]
