# Generated by Django 6.0 on 2025-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_development', '0004_alter_comanda_img_alter_osavatel_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Заявка на контакт',
                'verbose_name_plural': 'Заявки на контакт',
            },
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Имя основателя')),
                ('bio', models.TextField(verbose_name='Подробная биография')),
                ('image', models.ImageField(upload_to='founders/', verbose_name='Фото основателя')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Основатель',
                'verbose_name_plural': 'Основатели',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('image', models.ImageField(upload_to='services/', verbose_name='Фото услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Название компании')),
                ('footer_text', models.TextField(verbose_name='Описание/Слоган')),
                ('copyright_text', models.CharField(max_length=100, verbose_name='Все права защищены')),
                ('menu_services', models.CharField(max_length=100, verbose_name="Название ссылки 'Услуги'")),
                ('menu_it_school', models.CharField(max_length=100, verbose_name="Название ссылки 'Айти Школа'")),
                ('menu_projects', models.CharField(max_length=100, verbose_name="Название ссылки 'Проекты'")),
                ('menu_team', models.CharField(max_length=100, verbose_name="Название ссылки 'Команда'")),
                ('icon_1', models.ImageField(upload_to='icons/', verbose_name='Иконка 1')),
                ('icon_2', models.ImageField(upload_to='icons/', verbose_name='Иконка 2')),
                ('icon_3', models.ImageField(upload_to='icons/', verbose_name='Иконка 3')),
                ('icon_4', models.ImageField(upload_to='icons/', verbose_name='Иконка 4')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_photos/', verbose_name='Фото')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание / Должность')),
            ],
            options={
                'verbose_name': 'Член команды',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.DeleteModel(
            name='bidzaiavka',
        ),
        migrations.DeleteModel(
            name='Comanda',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Osavatel',
        ),
        migrations.DeleteModel(
            name='Uslugi',
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Наш проект', 'verbose_name_plural': 'Наши проекты'},
        ),
        migrations.RemoveField(
            model_name='logo',
            name='description',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='img',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='logo',
            name='image',
            field=models.ImageField(default=1, upload_to='logos/', verbose_name='Логотип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='name',
            field=models.CharField(default=11, max_length=35, verbose_name='Название логотипа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=1, verbose_name='Описание проекта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=1, upload_to='projects/', verbose_name='Фото проекта'),
            preserve_default=False,
        ),
    ]
