# Generated by Django 6.0 on 2025-12-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_development', '0005_contactrequest_founder_service_sitesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Соглащение условиями'),
        ),
    ]
