# Generated by Django 6.0 on 2025-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companymy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Название компании')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компания',
            },
        ),
        migrations.CreateModel(
            name='rabota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('Human', models.CharField(choices=[('worker', 'учитель'), ('work2', 'програмист'), ('work3', 'менеджер'), ('work4', 'продовец'), ('work5', 'Агент')], max_length=200, verbose_name='Кем хотите устроиться')),
                ('test', models.BooleanField(default=False, verbose_name='опыт работы')),
                ('money', models.IntegerField(verbose_name='Сколько хотите получать?')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='Что интересует')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('English', models.CharField(choices=[('java', 'Javascript'), ('Python', 'Python')], max_length=100, verbose_name='Изучаемый язык')),
                ('start_date', models.DateField(verbose_name='Дата обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил или нет')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=150, verbose_name='Кем работает')),
                ('salary', models.CharField(verbose_name='Сколько получает')),
                ('start_working_date', models.DateField(verbose_name='Дата работы')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Рабочии',
            },
        ),
        migrations.CreateModel(
            name='zaiavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Гмайл почта')),
                ('text', models.TextField(blank=True, null=True, verbose_name='что вас интересует')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'оставить заявку',
            },
        ),
    ]
