# Generated by Django 6.0 on 2025-12-12 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mer2', '0002_curs_onas_sertificat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curs',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
    ]
