# Generated by Django 6.0 on 2025-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mer1', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='img',
            field=models.ImageField(upload_to='загрузка фото', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='osavatel',
            name='img',
            field=models.ImageField(upload_to='загрузить', verbose_name='Оснаватели'),
        ),
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(upload_to='проекты', verbose_name='фото проекта'),
        ),
        migrations.AlterField(
            model_name='uslugi',
            name='img',
            field=models.ImageField(upload_to='услуга', verbose_name='фото'),
        ),
    ]
