# Generated by Django 6.0 on 2025-12-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mer3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cursu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='имия')),
                ('fristname', models.CharField(max_length=120, verbose_name='фамилия')),
                ('English', models.CharField(choices=[('java', 'Javascript'), ('Python', 'Python')], max_length=100, verbose_name='закончил')),
                ('data', models.DateField(verbose_name='запуск курса')),
                ('date', models.DateField(blank=True, null=True, verbose_name='длитильность')),
                ('paid', models.BooleanField(default=False, verbose_name='берем в работу?')),
            ],
            options={
                'verbose_name': 'управление курс',
                'verbose_name_plural': 'управление курсы',
            },
        ),
        migrations.CreateModel(
            name='rabotau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('Human', models.CharField(choices=[('worker', 'учитель'), ('work2', 'програмист'), ('work3', 'менеджер'), ('work4', 'продовец'), ('work5', 'Агент')], max_length=200, verbose_name='Кем работает')),
                ('test', models.BooleanField(default=False, verbose_name='опыт работы')),
                ('money', models.IntegerField(verbose_name='Сколько получет')),
                ('paid', models.BooleanField(default=False, verbose_name='уволить?')),
            ],
            options={
                'verbose_name': 'управление работа',
                'verbose_name_plural': 'управление работы',
            },
        ),
        migrations.CreateModel(
            name='studentu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('English', models.CharField(choices=[('java', 'опаздал'), ('Python', 'не опаздал')], max_length=100, verbose_name='опаздал или нет')),
                ('start_date', models.DateField(verbose_name='Дата обучения')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания обучения')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил или нет')),
                ('paid1', models.BooleanField(default=False, verbose_name='закончил или нет')),
            ],
            options={
                'verbose_name': 'управление Студент',
                'verbose_name_plural': 'управиление Студентов',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
