# Generated by Django 6.0 on 2025-12-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_School', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='curs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English', models.CharField(choices=[('java', 'Javascript'), ('Python', 'Python')], max_length=100, verbose_name='Изучаемый язык')),
                ('text', models.TextField(verbose_name='Описание')),
                ('data', models.DateField(verbose_name='запуск курса')),
                ('date', models.DateField(blank=True, null=True, verbose_name='длитильность')),
            ],
        ),
        migrations.CreateModel(
            name='onas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Что делат нас лучшим')),
                ('text', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'о нас',
                'verbose_name_plural': 'о нас',
            },
        ),
        migrations.CreateModel(
            name='sertificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100, verbose_name='Дарим серфтификат после оканчания курса')),
                ('text', models.TextField(verbose_name='описание')),
                ('oplata', models.BooleanField(default=False, verbose_name='Сертификат лицензирован')),
                ('oplatas', models.BooleanField(default=False, verbose_name='Международное признание')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Certificate', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Секртификат',
            },
        ),
    ]
