# Generated by Django 6.0 on 2025-12-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT_School', '0003_alter_curs_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Пункт "О нас"',
                'verbose_name_plural': 'Пункты "О нас"',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email почта')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Что вас интересует')),
            ],
            options={
                'verbose_name': 'Заявка от клиента',
                'verbose_name_plural': 'Заявки от клиентов',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сертификата')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_licensed', models.BooleanField(default=False, verbose_name='Сертификат лицензирован')),
                ('is_internationally_recognized', models.BooleanField(default=False, verbose_name='Международное признание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Certificate', verbose_name='Изображение сертификата')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python')], max_length=100, verbose_name='Изучаемый язык')),
                ('description', models.TextField(verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата запуска курса')),
                ('duration_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('desired_position', models.CharField(choices=[('teacher', 'Учитель'), ('programmer', 'Программист'), ('manager', 'Менеджер'), ('seller', 'Продавец'), ('agent', 'Агент')], max_length=200, verbose_name='Кем хотите устроиться')),
                ('has_experience', models.BooleanField(default=False, verbose_name='Опыт работы')),
                ('salary_expectation', models.IntegerField(verbose_name='Сколько хотите получать?')),
                ('interest', models.TextField(blank=True, null=True, verbose_name='Что интересует')),
            ],
            options={
                'verbose_name': 'Заявка на работу',
                'verbose_name_plural': 'Заявки на работу',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('position', models.CharField(max_length=150, verbose_name='Кем работает')),
                ('salary', models.IntegerField(verbose_name='Сколько получает')),
                ('start_working_date', models.DateField(verbose_name='Дата начала работы')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.DeleteModel(
            name='Companymy',
        ),
        migrations.DeleteModel(
            name='curs',
        ),
        migrations.DeleteModel(
            name='onas',
        ),
        migrations.DeleteModel(
            name='rabota',
        ),
        migrations.DeleteModel(
            name='sertificat',
        ),
        migrations.DeleteModel(
            name='work',
        ),
        migrations.DeleteModel(
            name='zaiavka',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='paid',
            new_name='is_paid',
        ),
        migrations.RemoveField(
            model_name='student',
            name='English',
        ),
        migrations.AddField(
            model_name='student',
            name='study_language',
            field=models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python')], default=1, max_length=100, verbose_name='Изучаемый язык'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала обучения'),
        ),
    ]
